// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortServiceClient interface {
	Get(ctx context.Context, in *PortId, opts ...grpc.CallOption) (*Port, error)
	Create(ctx context.Context, in *Port, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *Port, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Port, opts ...grpc.CallOption) (*Response, error)
	Upload(ctx context.Context, opts ...grpc.CallOption) (PortService_UploadClient, error)
	Download(ctx context.Context, in *Params, opts ...grpc.CallOption) (PortService_DownloadClient, error)
}

type portServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortServiceClient(cc grpc.ClientConnInterface) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) Get(ctx context.Context, in *PortId, opts ...grpc.CallOption) (*Port, error) {
	out := new(Port)
	err := c.cc.Invoke(ctx, "/proto.PortService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) Create(ctx context.Context, in *Port, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.PortService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) Update(ctx context.Context, in *Port, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.PortService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) Delete(ctx context.Context, in *Port, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.PortService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (PortService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &PortService_ServiceDesc.Streams[0], "/proto.PortService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &portServiceUploadClient{stream}
	return x, nil
}

type PortService_UploadClient interface {
	Send(*Port) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type portServiceUploadClient struct {
	grpc.ClientStream
}

func (x *portServiceUploadClient) Send(m *Port) error {
	return x.ClientStream.SendMsg(m)
}

func (x *portServiceUploadClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portServiceClient) Download(ctx context.Context, in *Params, opts ...grpc.CallOption) (PortService_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &PortService_ServiceDesc.Streams[1], "/proto.PortService/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &portServiceDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortService_DownloadClient interface {
	Recv() (*Port, error)
	grpc.ClientStream
}

type portServiceDownloadClient struct {
	grpc.ClientStream
}

func (x *portServiceDownloadClient) Recv() (*Port, error) {
	m := new(Port)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PortServiceServer is the server API for PortService service.
// All implementations should embed UnimplementedPortServiceServer
// for forward compatibility
type PortServiceServer interface {
	Get(context.Context, *PortId) (*Port, error)
	Create(context.Context, *Port) (*Response, error)
	Update(context.Context, *Port) (*Response, error)
	Delete(context.Context, *Port) (*Response, error)
	Upload(PortService_UploadServer) error
	Download(*Params, PortService_DownloadServer) error
}

// UnimplementedPortServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPortServiceServer struct {
}

func (UnimplementedPortServiceServer) Get(context.Context, *PortId) (*Port, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPortServiceServer) Create(context.Context, *Port) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPortServiceServer) Update(context.Context, *Port) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPortServiceServer) Delete(context.Context, *Port) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPortServiceServer) Upload(PortService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedPortServiceServer) Download(*Params, PortService_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}

// UnsafePortServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortServiceServer will
// result in compilation errors.
type UnsafePortServiceServer interface {
	mustEmbedUnimplementedPortServiceServer()
}

func RegisterPortServiceServer(s grpc.ServiceRegistrar, srv PortServiceServer) {
	s.RegisterService(&PortService_ServiceDesc, srv)
}

func _PortService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).Get(ctx, req.(*PortId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Port)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).Create(ctx, req.(*Port))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Port)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).Update(ctx, req.(*Port))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Port)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).Delete(ctx, req.(*Port))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PortServiceServer).Upload(&portServiceUploadServer{stream})
}

type PortService_UploadServer interface {
	SendAndClose(*Response) error
	Recv() (*Port, error)
	grpc.ServerStream
}

type portServiceUploadServer struct {
	grpc.ServerStream
}

func (x *portServiceUploadServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *portServiceUploadServer) Recv() (*Port, error) {
	m := new(Port)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PortService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Params)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortServiceServer).Download(m, &portServiceDownloadServer{stream})
}

type PortService_DownloadServer interface {
	Send(*Port) error
	grpc.ServerStream
}

type portServiceDownloadServer struct {
	grpc.ServerStream
}

func (x *portServiceDownloadServer) Send(m *Port) error {
	return x.ServerStream.SendMsg(m)
}

// PortService_ServiceDesc is the grpc.ServiceDesc for PortService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _PortService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PortService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PortService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PortService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _PortService_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _PortService_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "port.proto",
}
